### ISSUE TITLE
UWP Support

### ISSUE THREAD

**Issue by i2pacg** [Backendless/.NET-SDK#12]
any plans of porting this to UWP

**Comment by markpiller** [comment]
There is a build that targets .NET Core. That gives you the universality of using the API in any supported environment, doesn't  it?

**Comment by i2pacg** [comment]
Thanks for the quick response , which build is that , i tried installing through NuGet ,

**Comment by markpiller** [comment]
The nuget package includes multiple targets, one of them is for .net core 2.0

**Comment by i2pacg** [comment]
> The nuget package includes multiple targets, one of them is for .net core 2.0

indeed the netstandard 2.0 should work , but it kept failing to init backendless with an error exception "EngineIoClientDotNet 1.0.7 " ,, (same from github version)
i cloned the library from GitHub changed the dependency to the pre-release version of EngineIoClientDotNet , 
built the solution 
tried the dll in my project and it worked
