### ISSUE TITLE
Dependency broken (backendless does not compile)

### ISSUE THREAD

**Issue by vrescobar** [Backendless/.NET-SDK#14]
When I install Backendless.Net from the NuGet I see it displays no dependency in the list, just in the readme file, which is it inconvenient as it will fail to compile the project.

To reproduce create a new Xamarin Forms, try to add the Backendless package and try to compile.

The following error will be displayed:

```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2,2): Error XA2002: Can not resolve reference: `SocketIoClientDotNet.netstandard2.0`, referenced by `Backendless`. Please add a NuGet package or assembly reference for `SocketIoClientDotNet.netstandard2.0`, or remove the reference to `Backendless`. (XA2002) (secretario.Android)
```

Installing manually [SocketIoClientDotNet](https://github.com/Quobject/SocketIoClientDotNet/) does not solve the issue as it will fail again with the same error.

Note this is a follow up from #13

**Comment by holailusoria** [comment]
This has been fixed
