### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by abraaocaldas** [Backendless/.NET-SDK#4]
Anyone already tried to compile this project?

Missing references all over the place... Not even close to good.

**Comment by markpiller** [comment]
What version of VS do you compile it with? Which sln did you open? Not sharing any details does not make it easier helping you solve the problem..

**Comment by abraaocaldas** [comment]
In Visual Studio 2013 and Visual Studio 2015, when I try to use it on a Console application (.Net 4.5 ) project, the build fails, I'm trying to add it as reference of the main project. Attached a print screen to better view :)

![testless](https://cloud.githubusercontent.com/assets/3661806/12707213/80485822-c867-11e5-806a-91e68786f8e7.jpg)
.

**Comment by abraaocaldas** [comment]
In Visual Studio 2013 and Visual Studio 2015, when I try to use it on a Console application (.Net 4.5 ) project, the build fails, I'm trying to add it as reference of the main project. Attached a print screen to better view :)
![testless](https://cloud.githubusercontent.com/assets/3661806/12707233/b21e1f58-c867-11e5-8339-2b54ca4867ff.jpg)

**Comment by markpiller** [comment]
Did you import existing project for the backendless assembly or created your own own? Backendless.NET.csproj should has everything pre-configured for a build.

Try adding PURE_CLIENT_LIB to the conditional compilation symbols.

**Comment by abraaocaldas** [comment]
The same problem.

Reproduction path
Create a Console application (.Net 4.5)
Solution -> Add -> Existing project -> Add Backendless project
Try to compile.

**Comment by markpiller** [comment]
The moment I added PURE_CLIENT_LIB to the conditional compilation symbols, it built without any problems:
![backendless-proj-config](https://cloud.githubusercontent.com/assets/120929/12707407/a0c097ee-c859-11e5-9638-700c8db74040.png)

**Comment by abraaocaldas** [comment]
Ok, it worked! :+1: 
It's good to put this in the readme ? Because I don't think the current use is an "out-of-box" experience.

PS: I just used the source code because the precompiled dll from backendless server is not working, when you try to register a user it just throws a "Stackoverflow" exception using the exact same code with the compiled source code from git works perfectly!

**Comment by markpiller** [comment]
Thanks for the feedback. We'll get a readme put together. Need to figure out why the precompiled didn't work. The vision was that users would compile their projects against that.
