### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by ndastur** [Backendless/.NET-SDK#6]
Hi. I have come across your service and would like to use it in a Xamarin .Net project targetting android and ios. Do you have / or intend to have a NuGET package to install for these platforms?

Thanks

**Comment by ramilbgd** [comment]
This would be very relevant

**Comment by SharpMobileCode** [comment]
Even though the title of the ReadMe says this is compatible with Xamarin, it obviously is not.  The Nuget package is incompatible with .NetStandard 2.0, nor is it compatible with a Xamarin.iOS or Xamarin.Android project.

On top of that, there is no `async/await` support and the API looks like it was written by a Java developer.  When I found this service, I was excited, but now it's just a disappointment.  The .NET Documentation is incomplete as well.

**Comment by markpiller** [comment]
The Xamarin support is still work in progress. The .netstandard project is in [github](https://github.com/Backendless/.NET-SDK/tree/master/Projects/Backendless.NET.Standard20), but I have not pushed it to nuget yet. I am waiting till the author of SocketDotNetIO library creates a deployment target for .netstandard in NuGet (there is an [open issue](https://github.com/Quobject/SocketIoClientDotNet/issues/167) for them). Support for `async/await` will come a bit later. As for the docs, you can find them at: https://backendless.com/docs/dotnet/doc.html

**Comment by markpiller** [comment]
The NuGet package has been updated. The latest version (5.1.0) now includes support for the .netstandard2.0 framework. Has been tested with Xamarin Android, works well.

**Comment by markpiller** [comment]
Just published 5.1.1 in NuGet. This build provides `async` support for all Backendless APIs
